### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by rutuja1409** [BullsEye0/Happy-Birthday#1]
Hey can you help me in this. Its giving me sytax error at time.sleep(1). when i removed this line it then gave syntax error on next time where we have defined happy birthday function: def happy_birthday()
Can you please help @BullsEye0

**Comment by BullsEye0** [comment]
Just let the line there.. 
Sometimes I hated it when I make my tools public. (I won't anymore..!)
They are not for changing. Just make your own tools.!
Stay away from mine.!
